# VARIABLES
sonarqube_url: &__SONARQUBE_URL__ ((sonarqube-url))
sonarqube_token: &__SONARQUBE_TOKEN__ ((sonarqube-token))
sonarqube_project_name: &__SONARQUBE_COMPONENT__ ((sonarqube-component))

resource_types:
- name: sonarqube-notifier
  type: docker-image
  source:
    repository: lgohr/sonarqube
    tag: latest

resources:
- name: concourse-template
  type: git
  source:
    uri: https://github.com/elgohr/concourse-templates
    branch: master
- name: sonar-results
  type: sonarqube-notifier
  source:
    target: *__SONARQUBE_URL__
    sonartoken: *__SONARQUBE_TOKEN__
    component: *__SONARQUBE_COMPONENT__
    metrics: ncloc,complexity,violations,coverage

jobs:
- name: publish
  plan:
  - aggregate:
    - get: sonar-results
      trigger: true
    - get: concourse-template
  - task: publish
    file: concourse-template/sonarqube-notification/job.yml
